### ISSUE TITLE
Nextcloud docker (Collabora) DNS does not resolve (with possible solution)

### ISSUE THREAD

**Issue by aaaskew** [nextcloud/vm#1213]
Collabora docker image incorrectly requires Internet gateway port forwarding and loopback connection from docker image to external Internet gateway IP address back to the Nextcloud server due to bad default DNS setup.

Can the VM be improved or at least FAQ documentation.

## Steps to reproduce
1. Install Nextcloud VM with Collabora docker image.
2. Set fixed IP address, gateway and DNS server in Ubuntu netplan config file. Note DNS server is on another server in the subnet.
3. Stop port forwarding on Internet gateway to Nextcloud server on 192.168.0.100:443.
4. Try to edit a document using Nextcloud Collabora

## Expected behaviour
It is possible to edit a document

## Actual behaviour
Collabora cannot open the document. nextcloud.domain.net inside Collabora docker image resolves to external IP address of Internet gateway. This is not good as it means that all Collabora document opens are going via the Internet gateway when they can be connected directly on the VM.

The problem is with systemd-resolve or docker settings. The VM /etc/hosts file does not appear to be used inside the Collabora docker image and it gets DNS settings from systemd-resolve which has per-interface DNS resolvers. Setting a fixed DNS server against an interface in Netplan only affects that interface and not the docker interface.

I fixed the problem by setting the systemd-resolve default DNS server. See proposed fix below. Maybe there is a better way of solving this?

Please fix or document in FAQ what needs to be done

## Server configuration

**Nextcloud server version:** (see your admin page)
18.0.4

**Server OS** (Ubuntu server is default)
Default - Ubuntu 18.04.4

**How did you install the VM?** (Scripted install from master **OR** Released version)
Release install

## Network
**Do you use DHCP?**
No

**Is port 80 and/or 443 open?**
On Internet gateway, port forwarding done during installation only. Removed afterwards.

#### Netplan config file (/etc/netplan/01-netcfg.yaml)
```
network:
   version: 2
   renderer: networkd
   ethernets:
       enp0s3: #object name
         dhcp4: no # dhcp v4 disable
         dhcp6: no # dhcp v6 disable
         addresses: [192.168.0.100/24] # client IP address
         gateway4: 192.168.0.1 # gateway address
         nameservers:
           addresses: [192.168.0.50] #name servers
```

#### Log file (docker logs xxx)
```
wsd-00006-00036 2020-04-27 17:10:00.790250 [ docbroker_001 ] ERR  Cannot get file info from WOPI storage uri [https://nextcloud.domain.net/index.php/apps/richdocuments/wopi/files/xxx?access_token=xxx&access_token_ttl=0]. Error: Connection refused| wsd/Storage.cpp:564
```

#### SystemD resolver before fix (systemd-resolve --status)
```
Global
         DNS Servers: 9.9.9.9 ...
          DNSSEC NTA: 10.in-addr.arpa
                      16.172.in-addr.arpa
...
Link 3 (docker0)
      Current Scopes: none
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: no
    DNSSEC supported: no

Link 2 (enp0s3)
      Current Scopes: DNS
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
         DNS Servers: 192.168.0.50
```

#### Proposed fix (/etc/systemd/resolved.conf)
```
...
[Resolve]
DNS=192.168.0.50
...
```
