### ISSUE TITLE
Temporary failure resolving error on Ubuntu, LDAP connection lost

### ISSUE THREAD

**Issue by StefanSa** [nextcloud/vm#2432]
### Steps To Reproduce

Hi there,
first thank you for this nextcloud VM.
I originally come from here with the problem "LDAP connection lost".  https://github.com/nextcloud/server/issues/36281
But i had to realize that this is only partially a problem of nextcloud.
This is probably more a problem of Ubuntu / Netzplan. From time to time only the name resolution goes to external and not to the internal DNS servers. For this reason no LDAP connection can be established.
Currently we have temporarily solved the problem by adding the internal DNS servers to the "host" file.

How to solve the problem permanently and correctly mint netplan ?
This problem seems to exists several times if you search for it for example at "ask Ubuntu".
https://askubuntu.com/questions/1428418/ubuntu-22-04-temporary-failure-in-name-resolution-for-local-network
https://askubuntu.com/questions/1045278/ubuntu-server-18-04-temporary-failure-in-name-resolution
https://askubuntu.com/questions/1444317/temporary-failure-in-name-resolution-after-upgrading-22-04-to-22-10
https://askubuntu.com/questions/1361191/ubuntu-20-04-upgrades-dns-name-resolution-fails-on-internal-network

Thanks for any help
Stefan

### Expected Result

DNS name resolution without problems for both internal and external DNS servers.

### Actual Result

only external DNS name resolution works. Temporary solution, add internal DNS server to hostfile.

### Build Version

latest Version via Update

### Environment

By downloading the VM

**Comment by enoch85** [comment]
Hi,

Thanks for your report.

Running LDAP it's usually pretty crucial that you run local DNS servers (Windows hey). To solve that you can do it in the systemd-resolved and then reboot the server, or service.

You can also set static IP and choice your own DNS servers during setup. We have a script for thatt in the menu.

Hope it helps!

**Comment by StefanSa** [comment]
Hi Daniel,
the static DNS IP we had initially set at the beginning with your script, this worked so far without problem.
However, for some reason the name resolution to the internal DNS server no longer works sporadically.
As already mentioned, only the current hostfile helped here.

this netplan configuration worked at the beginning without any problem:
```
network:
   version: 2
   ethernets:
       ens32: #object name
         dhcp4: false # dhcp v4 disable
         dhcp6: false # dhcp v6 disable
         addresses:
         - 172.16.66.170/24
         routes:
          - to: default
            via: 172.16.66.1
         nameservers:
           addresses: [172.16.34.10,172.16.34.12]
           search: [xxxxx1.local, xxxx2.local]
```
I will do this with the "systemd-resolved" as you recommended.
Greetings from Germany to Sweden
