### ISSUE TITLE
[not really a bug] Installing on Proxmox/OVH [Soyoustart]

### ISSUE THREAD

**Issue by fcorbelli** [nextcloud/vm#2441]
### Steps To Reproduce

Installing the virtual machine with a failover IP on OVH/Soyoustart server does not work.
The VM start, but cannot resolve anything (no DHCP of course), neither the static IP configuration works (read below why and how to fix)

### Expected Result

Be able to manually edit the .yaml (or choose some kind of checkbox to enforce this behayviour)

### Actual Result

Impossible to activate NIC=> cannot configure the VM => abort

### Additional Context

The problem lies in the peculiarity of the .yaml file to use a "strange" IP router, mandatory for OVH/Soyoustart
A "standard" OVH server have 1 "real" IP, and N "other" IPs (the failover).
The normal gateway is the IP.254

In this example the "first" IP is 176.178.179.180 => the gateway become 176.178.179.**254**
With a failover IP 37.1.2.3, on  00:51:52:53:54:55 (this is a ESXi legacy, whatever it is on proxmox)

The "routes" section is the key: it's mandatory (AFAIK)

Something like that (on ens19)
```
network:
   version: 2
   ethernets:
       ens19: #object name
         dhcp4: false # dhcp v4 disable
         dhcp6: false # dhcp v6 disable
         addresses: [37.1.2.3/32]
         match:
            macaddress: 00:51:52:53:54:55
         nameservers:
           addresses: [8.8.8.8,208.67.222.222]
         routes:
         - to: 0.0.0.0/0
           via: 176.178.179.254 
           on-link: true
```

My usual "quick-and-dirrrrrty" trick is
- control-C to enter "standard" shell
- changing the netplan .yaml by hand
- netplan apply
- launch another shell (alt f2)
- run the "normal" installation process

Of course, nothing impossible for a fairly experienced user, but I think it represents a blocking problem for those less accustomed
Kind regards

### Build Version

25.0.2

### Environment

By downloading the VM

### Environment Details

- Proxmox 7.3.4
- Running on OVH/Soyoustart barematel
- 1 "real" IP + N failover, running on failover IP
